title: "Global Energy Dashboard 🌍⚡"
description: "An analytical view of global energy usage trends and efficiency."
show_downloads: True
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation Links (Optional)
header_pages:
  - index.md
  - about.md
  - insights.md
  - recommendations.md
  - methodology.md

# Favicon (Set after adding it to assets)
favicon: "assets/images/output-onlinegiftools.gif"
